# WEATHER PREDICTION MODEL

In [130]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pickle
import numpy as np

## Import & Load the Dataset

In [21]:
df = pd.read_csv("small_weather_dataset.csv")
df.head()

DATE  MONTH  BASEL_temp_mean  BASEL_humidity  BASEL_pressure  \
0  20000101      1              2.9            0.89          1.0286   
1  20000102      1              3.6            0.87          1.0318   
2  20000103      1              2.2            0.81          1.0314   
3  20000104      1              3.9            0.79          1.0262   
4  20000105      1              6.0            0.90          1.0246   

   BASEL_precipitation  BASEL_sunshine  RainTomorrow  
0                 0.03             0.0             1  
1                 0.00             0.0             1  
2                 0.00             3.7             0  
3                 0.35             6.9             1  
4                 0.07             3.7             1

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   DATE                 200 non-null    int64  
 1   MONTH                200 non-null    int64  
 2   BASEL_temp_mean      200 non-null    float64
 3   BASEL_humidity       200 non-null    float64
 4   BASEL_pressure       200 non-null    float64
 5   BASEL_precipitation  200 non-null    float64
 6   BASEL_sunshine       200 non-null    float64
 7   RainTomorrow         200 non-null    int64  
dtypes: float64(5), int64(3)
memory usage: 12.6 KB


In [27]:
 df_dumies = pd.get_dummies(df,columns=['DATE', 'MONTH', 'BASEL_temp_mean', 'BASEL_humidity','BASEL_pressure','BASEL_precipitation','BASEL_sunshine','RainTomorrow'])
 print(df_dumies)


     DATE_20000101  DATE_20000102  DATE_20000103  DATE_20000104  \
0             True          False          False          False   
1            False           True          False          False   
2            False          False           True          False   
3            False          False          False           True   
4            False          False          False          False   
..             ...            ...            ...            ...   
195          False          False          False          False   
196          False          False          False          False   
197          False          False          False          False   
198          False          False          False          False   
199          False          False          False          False   

     DATE_20000105  DATE_20000106  DATE_20000107  DATE_20000108  \
0            False          False          False          False   
1            False          False          False          Fal

In [134]:
X = df.drop(columns=["RainTomorrow", "DATE"])  
y = df["RainTomorrow"]

In [33]:
df.head()

DATE  MONTH  BASEL_temp_mean  BASEL_humidity  BASEL_pressure  \
0  20000101      1              2.9            0.89          1.0286   
1  20000102      1              3.6            0.87          1.0318   
2  20000103      1              2.2            0.81          1.0314   
3  20000104      1              3.9            0.79          1.0262   
4  20000105      1              6.0            0.90          1.0246   

   BASEL_precipitation  BASEL_sunshine  RainTomorrow  
0                 0.03             0.0             1  
1                 0.00             0.0             1  
2                 0.00             3.7             0  
3                 0.35             6.9             1  
4                 0.07             3.7             1

In [35]:
df.tail()

DATE  MONTH  BASEL_temp_mean  BASEL_humidity  BASEL_pressure  \
195  20000714      7             13.7            0.83          1.0116   
196  20000715      7             12.6            0.78          1.0124   
197  20000716      7             12.7            0.81          1.0166   
198  20000717      7             14.8            0.71          1.0192   
199  20000718      7             16.7            0.66          1.0191   

     BASEL_precipitation  BASEL_sunshine  RainTomorrow  
195                 1.09             0.1             1  
196                 0.64             2.4             1  
197                 1.17             2.6             1  
198                 0.00            12.0             0  
199                 0.00            11.8             0

In [37]:
df.columns

Index(['DATE', 'MONTH', 'BASEL_temp_mean', 'BASEL_humidity', 'BASEL_pressure',
       'BASEL_precipitation', 'BASEL_sunshine', 'RainTomorrow'],
      dtype='object')

In [43]:
df.shape

(200, 8)

In [45]:
df.dtypes

DATE                     int64
MONTH                    int64
BASEL_temp_mean        float64
BASEL_humidity         float64
BASEL_pressure         float64
BASEL_precipitation    float64
BASEL_sunshine         float64
RainTomorrow             int64
dtype: object

In [47]:
df.describe

<bound method NDFrame.describe of          DATE  MONTH  BASEL_temp_mean  BASEL_humidity  BASEL_pressure  \
0    20000101      1              2.9            0.89          1.0286   
1    20000102      1              3.6            0.87          1.0318   
2    20000103      1              2.2            0.81          1.0314   
3    20000104      1              3.9            0.79          1.0262   
4    20000105      1              6.0            0.90          1.0246   
..        ...    ...              ...             ...             ...   
195  20000714      7             13.7            0.83          1.0116   
196  20000715      7             12.6            0.78          1.0124   
197  20000716      7             12.7            0.81          1.0166   
198  20000717      7             14.8            0.71          1.0192   
199  20000718      7             16.7            0.66          1.0191   

     BASEL_precipitation  BASEL_sunshine  RainTomorrow  
0                   0.03        

In [49]:
df.isnull().sum()

DATE                   0
MONTH                  0
BASEL_temp_mean        0
BASEL_humidity         0
BASEL_pressure         0
BASEL_precipitation    0
BASEL_sunshine         0
RainTomorrow           0
dtype: int64

In [51]:
df.duplicated().sum()

0

In [53]:
df.sample()

DATE  MONTH  BASEL_temp_mean  BASEL_humidity  BASEL_pressure  \
1  20000102      1              3.6            0.87          1.0318   

   BASEL_precipitation  BASEL_sunshine  RainTomorrow  
1                  0.0             0.0             1

In [57]:
df['BASEL_temp_mean'].unique()

array([ 2.9,  3.6,  2.2,  3.9,  6. ,  4.2,  4.7,  5.6,  4.6,  2.4,  3.2,
        1.7,  0.6, -1.3, -0.4,  0.9,  4.5,  0.4,  2.5,  3.1,  2. , -4. ,
       -6.5, -6.8, -5.2, -1.7,  7.4, 10. ,  8.1,  5.4,  5.5,  5.2,  3.3,
        6.9,  7.6, 11.4,  6.2,  2.8,  7. ,  8.3,  4.4,  2.1,  1.9,  1.3,
        2.7,  3.5,  9.5,  9. , 11. ,  5.8,  7.5,  5.1,  6.4,  9.2, 14.1,
       10.3, 11.1,  9.3, 10.5,  6.5,  8.2, 10.9,  8. ,  5.7,  3.8,  8.7,
        7.1, 12.9, 11.5,  8.6,  5.9,  9.1, 10.2,  9.6,  8.4, 12.5, 10.1,
       16.8, 18.4, 14.8, 13.5, 17.8, 16.3, 14.9, 11.8, 15.1, 17. , 16.5,
       17.5, 16.7, 18. , 16.9, 18.8, 20. , 20.5, 16.2, 19.4, 20.9, 17.3,
       13.6, 12. , 13. , 12.8, 12.4, 14.4, 17.4, 13.4, 21.7, 22.8, 23.4,
       19.6, 15.7, 22.9, 22. , 17.7, 18.3, 20.6, 21.3, 20.8, 17.9, 19.7,
       23. , 25.1, 24.6, 18.7, 13.7, 14.6, 15.5, 14.7, 17.1, 23.8, 19.9,
       15.4, 16.1, 14.5, 13.2, 12.6, 12.7])

In [61]:
df['BASEL_temp_mean'].nunique()

138

In [63]:
df['BASEL_humidity'].unique()

array([0.89, 0.87, 0.81, 0.79, 0.9 , 0.85, 0.84, 0.88, 0.91, 0.77, 0.78,
       0.8 , 0.83, 0.69, 0.72, 0.74, 0.86, 0.61, 0.71, 0.76, 0.65, 0.7 ,
       0.67, 0.82, 0.68, 0.64, 0.59, 0.54, 0.56, 0.53, 0.66, 0.73, 0.5 ,
       0.6 , 0.62, 0.63, 0.55, 0.75, 0.57, 0.58, 0.48])

In [65]:
df['BASEL_humidity'].nunique()

41

In [67]:
df['BASEL_pressure'].unique()

array([1.0286, 1.0318, 1.0314, 1.0262, 1.0246, 1.0244, 1.0267, 1.0248,
       1.0243, 1.0337, 1.0373, 1.0319, 1.0226, 1.023 , 1.0311, 1.0346,
       1.0328, 1.0307, 1.0333, 1.0297, 1.017 , 1.0151, 1.0235, 1.0302,
       1.0354, 1.0342, 1.0269, 1.0166, 1.0224, 1.0304, 1.0221, 1.0361,
       1.0391, 1.0343, 1.0274, 1.0239, 1.0281, 1.0264, 1.025 , 1.0252,
       1.0197, 1.0103, 1.0134, 1.0127, 1.0123, 1.031 , 1.0273, 1.0289,
       1.0306, 1.0287, 1.0315, 1.0283, 1.0219, 1.0179, 1.0099, 1.0258,
       1.0185, 1.0234, 1.0357, 1.0322, 1.0299, 1.0278, 1.0225, 1.026 ,
       1.0242, 1.032 , 1.0285, 1.0268, 1.0257, 1.0217, 1.019 , 1.0148,
       1.014 , 1.0158, 1.0089, 1.0104, 1.0083, 1.0133, 1.0088, 1.008 ,
       1.0028, 0.992 , 0.9942, 1.0063, 1.0216, 1.0097, 1.0059, 0.9987,
       0.9972, 1.0026, 1.0007, 1.0029, 1.0023, 1.0076, 1.0112, 1.0132,
       1.015 , 1.016 , 1.0114, 1.0154, 1.013 , 1.0078, 1.0174, 1.0198,
       1.0171, 1.0161, 1.0175, 1.0145, 1.0152, 1.0183, 1.0172, 1.0207,
      

In [69]:
df['BASEL_pressure'].nunique()

151

In [71]:
df['BASEL_precipitation'].unique()

array([0.03, 0.  , 0.35, 0.07, 0.65, 0.09, 0.12, 0.42, 0.02, 0.13, 0.99,
       0.01, 0.44, 1.27, 0.04, 0.15, 1.22, 0.48, 0.39, 0.25, 0.14, 0.45,
       0.9 , 0.36, 0.53, 0.56, 0.05, 0.17, 0.24, 0.47, 0.29, 0.54, 0.28,
       0.16, 1.38, 0.37, 0.5 , 0.1 , 0.7 , 0.73, 0.11, 0.19, 0.32, 1.5 ,
       0.52, 1.08, 0.38, 4.11, 0.08, 0.46, 0.79, 0.91, 0.6 , 0.26, 1.24,
       0.61, 0.59, 1.09, 0.64, 1.17])

In [73]:
df['BASEL_precipitation'].nunique()

60

In [75]:
df['BASEL_sunshine'].unique()

array([ 0. ,  3.7,  6.9,  5.7,  4.3,  7.5,  7.6,  2.8,  0.3,  0.1,  0.7,
        3.2,  8.1,  8.4,  2.2,  1.6,  5.8,  2.9,  8.3,  3. ,  1.9,  8. ,
        0.4,  1.2,  1.5,  0.9,  8.5,  9.6,  1.8,  9. ,  3.8,  7.1, 10.6,
       10.5,  2.4,  3.9,  2.1,  5.9,  9.8,  4. , 11.1, 11. ,  8.2,  0.6,
        5.3, 10.7,  4.8, 12.3, 12.4,  4.7,  6.5,  9.4,  1. , 12. ,  9.2,
        8.6,  2.5, 12.2, 11.9,  4.1, 11.2,  7. ,  4.6,  8.8,  6.1, 12.8,
       10.1,  2.6,  3.3,  4.4, 13.8, 13.6, 12.5, 11.8, 11.4, 14.6, 14. ,
        6. ,  7.4, 14.8, 15.3, 15. , 14.1,  1.4, 13.1,  4.9, 13. , 12.9,
       10.8, 13.2,  3.5])

In [77]:
df['BASEL_sunshine'].nunique()

91

In [79]:
df['RainTomorrow'].unique()

array([1, 0], dtype=int64)

In [81]:
df['RainTomorrow'].nunique()

2

## Clean the Data

In [83]:
df.dropna(inplace=True)

In [85]:
df.fillna(0)

DATE  MONTH  BASEL_temp_mean  BASEL_humidity  BASEL_pressure  \
0    20000101      1              2.9            0.89          1.0286   
1    20000102      1              3.6            0.87          1.0318   
2    20000103      1              2.2            0.81          1.0314   
3    20000104      1              3.9            0.79          1.0262   
4    20000105      1              6.0            0.90          1.0246   
..        ...    ...              ...             ...             ...   
195  20000714      7             13.7            0.83          1.0116   
196  20000715      7             12.6            0.78          1.0124   
197  20000716      7             12.7            0.81          1.0166   
198  20000717      7             14.8            0.71          1.0192   
199  20000718      7             16.7            0.66          1.0191   

     BASEL_precipitation  BASEL_sunshine  RainTomorrow  
0                   0.03             0.0             1  
1                   0.00             0.0             1  
2                   0.00             3.7             0  
3                   0.35             6.9             1  
4                   0.07             3.7             1  
..                   ...             ...           ...  
195                 1.09             0.1             1  
196                 0.64             2.4             1  
197                 1.17             2.6             1  
198                 0.00            12.0             0  
199                 0.00            11.8             0  

[200 rows x 8 columns]

In [87]:
df.drop_duplicates()

DATE  MONTH  BASEL_temp_mean  BASEL_humidity  BASEL_pressure  \
0    20000101      1              2.9            0.89          1.0286   
1    20000102      1              3.6            0.87          1.0318   
2    20000103      1              2.2            0.81          1.0314   
3    20000104      1              3.9            0.79          1.0262   
4    20000105      1              6.0            0.90          1.0246   
..        ...    ...              ...             ...             ...   
195  20000714      7             13.7            0.83          1.0116   
196  20000715      7             12.6            0.78          1.0124   
197  20000716      7             12.7            0.81          1.0166   
198  20000717      7             14.8            0.71          1.0192   
199  20000718      7             16.7            0.66          1.0191   

     BASEL_precipitation  BASEL_sunshine  RainTomorrow  
0                   0.03             0.0             1  
1                   0.00             0.0             1  
2                   0.00             3.7             0  
3                   0.35             6.9             1  
4                   0.07             3.7             1  
..                   ...             ...           ...  
195                 1.09             0.1             1  
196                 0.64             2.4             1  
197                 1.17             2.6             1  
198                 0.00            12.0             0  
199                 0.00            11.8             0  

[200 rows x 8 columns]

## Train the Model

In [123]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)



LogisticRegression(max_iter=1000)

### Accuracy check

In [121]:
accuracy = model.score(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")

Test Accuracy: 0.95


##  Save the Model:

In [115]:
with open("weather_model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully as 'weather_model.pkl'")


Model saved successfully as 'weather_model.pkl'


In [117]:
with open('weather_model.pkl', 'rb') as file:
 loaded_model = pickle.load(file)
 print("Model loaded successfully!")

Model loaded successfully!
